FROM ubuntu:20.04 AS installer

ARG INSTALLER="Xilinx_Vivado_Lab_Lin_2021.2_1021_0703.tar.gz"

RUN mkdir /xilinx
WORKDIR /xilinx

RUN uname -a

ADD Xilinx_Vivado_Lab_Lin_2021.2_1021_0703.tar.gz /xilinx/

RUN cd Xilinx_Vivado_* && \
    ./xsetup \
	--agree XilinxEULA,3rdPartyEULA \
	--batch Install \
	--edition "Vivado Lab Edition (Standalone)" \
	--location /installed

RUN ls /installed
RUN ls /installed/Vivado_Lab/2021.2
RUN ls /installed/Vivado_Lab/2021.2/bin/unwrapped/lnx64.o/

FROM ubuntu:20.04

RUN echo /xilinx/lib/ >> /etc/ld.so.conf



COPY --from=installer /installed/Vivado_Lab/2021.2/bin/unwrapped/lnx64.o/rdi_xsdb /xilinx/bin/
COPY --from=installer /installed/Vivado_Lab/2021.2/lib/lnx64.o/libtcl8.5.so \
                      /installed/Vivado_Lab/2021.2/lib/lnx64.o/libtcltcf.so /xilinx/lib/

COPY --from=installer /installed/Vivado_Lab/2021.2/tps/tcl/tcl8.5 \
                     /xilinx/tcl8.5

COPY --from=installer /installed/Vivado_Lab/2021.2/tps/tcl/tcllib1.11.1 \
                     /xilinx/tcllib1.11.1

COPY --from=installer /installed/Vivado_Lab/2021.2/scripts/xsdb \
                     /xilinx/xsdb-lib


RUN ldconfig

ENV TCL_LIBRARY=/xilinx/tcl8.5
ENV TCLLIBPATH="/xilinx/xsdb-lib /xilinx/tcllib1.11.1"

ENTRYPOINT ["/xilinx/bin/rdi_xsdb"]
